language: c

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: GFsc99IHEIY3pGbNrYInR+N10CXpzGwnULkeX8Ol6o+18e2VmRrkCfWM/vSi48ka7g2q/rqzoQZnpwt2K2Dr8ctDAbIoQ2jS77vr9ws9YkpWEGwJVdXZIyC2OR3FgTihT2KSU4DTKimsOkJ7TrTSsRvWM9vzY3seBxBT/xaqg60=

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended

install:
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - set -e
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
